const oathAuthor = {
  marginTop: "10px",
  color: "#7dd3fc",
  fontSize: "13px",
  letterSpacing: "1px",
};

const oathCategory = {
  marginTop: "6px",
  display: "inline-block",
  padding: "4px 10px",
  borderRadius: "999px",
  background: "rgba(125,211,252,.08)",
  border: "1px solid rgba(125,211,252,.25)",
  color: "#c7d2fe",
  fontSize: "11px",
};
export const oaths = [
  { text: "A calm blade cuts deeper than an angry one.", author: "Inspired by Bushidō", category: "Samurai" },
  { text: "Victory begins long before the battlefield.", author: "Inspired by Miyamoto Musashi", category: "Samurai" },
  { text: "The mountain yields only to those who keep climbing.", author: "Journey", category: "Journey" },
  { text: "Train until silence speaks for your skill.", author: "Samurai Wisdom", category: "Samurai" },
  { text: "Storms reveal the strength hidden by calm seas.", author: "Sailor's Wisdom", category: "Journey" },
  { text: "Honor survives longer than triumph.", author: "Bushidō", category: "Samurai" },
  { text: "One steady step defeats a thousand empty dreams.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "The sword obeys the heart before the hand.", author: "Bushidō", category: "Samurai" },
  { text: "Do not fear the path because you walk it alone.", author: "Inspired by Vinland Saga", category: "Anime" },
  { text: "A warrior who laughs has not forgotten hope.", author: "Inspired by Gintama", category: "Anime" },

  { text: "Master yourself before seeking to master others.", author: "Inspired by Stoicism", category: "History" },
  { text: "A promise carried through hardship becomes destiny.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "Every sunrise grants another chance to sharpen your spirit.", author: "Journey", category: "Journey" },
  { text: "A dull blade blames the stone.", author: "Samurai Wisdom", category: "Samurai" },
  { text: "The sea rewards those who refuse to stop rowing.", author: "Sailor's Wisdom", category: "Journey" },
  { text: "The strongest fortress is a disciplined mind.", author: "Inspired by Marcus Aurelius", category: "History" },
  { text: "Protect what matters even when no one is watching.", author: "Inspired by One Piece", category: "Anime" },
  { text: "Patience is the quiet edge of every great sword.", author: "Bushidō", category: "Samurai" },
  { text: "Small victories build unbreakable warriors.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "A calm sea teaches little.", author: "Journey", category: "Journey" },

  { text: "Stand up one more time than you fall.", author: "Inspired by Naruto", category: "Anime" },
  { text: "The journey shapes the traveler more than the destination.", author: "Journey", category: "Journey" },
  { text: "Strength without kindness is only force.", author: "Bushidō", category: "Samurai" },
  { text: "Steel rusts when forgotten. So does resolve.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "Walk quietly. Let your deeds announce your arrival.", author: "Inspired by Musashi", category: "History" },
  { text: "The longest road is crossed one step at a time.", author: "Journey", category: "Journey" },
  { text: "The moon watches every warrior equally.", author: "Samurai Wisdom", category: "Samurai" },
  { text: "Protect your smile as fiercely as your dreams.", author: "Inspired by Gintama", category: "Anime" },
  { text: "The strongest roots grow beneath unseen ground.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "Discipline remembers when motivation forgets.", author: "Modern Warrior", category: "Warrior" },

  { text: "The blade grows brighter through resistance.", author: "Bushidō", category: "Samurai" },
  { text: "The ocean never asks if you're ready.", author: "Journey", category: "Journey" },
  { text: "Respect is earned through consistency.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "Carry your scars like medals earned honestly.", author: "Inspired by Berserk", category: "Anime" },
  { text: "A quiet heart makes fearless decisions.", author: "Bushidō", category: "Samurai" },
  { text: "Storms eventually become stories.", author: "Journey", category: "Journey" },
  { text: "A true warrior competes with yesterday.", author: "Inspired by Stoicism", category: "History" },
  { text: "Stand firm when the world begins to shake.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "The strongest fire begins with a single spark.", author: "Inspired by One Piece", category: "Anime" },
  { text: "Walk your road without borrowing another's footsteps.", author: "Inspired by Musashi", category: "History" },

  { text: "Even the moon has survived countless nights.", author: "Journey", category: "Journey" },
  { text: "Never polish your sword more than your character.", author: "Bushidō", category: "Samurai" },
  { text: "Fear bows before preparation.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "Hope is strongest when carried through darkness.", author: "Inspired by Vinland Saga", category: "Anime" },
  { text: "The wind favors those already sailing.", author: "Journey", category: "Journey" },
  { text: "The greatest duel is against your weaker self.", author: "Inspired by Stoicism", category: "History" },
  { text: "Walk forward even when the path disappears.", author: "Warrior Wisdom", category: "Warrior" },
  { text: "An empty boast is lighter than a feather.", author: "Bushidō", category: "Samurai" },
  { text: "Dream boldly. Train quietly.", author: "Inspired by Anime", category: "Anime" },
  { text: "Leave every sunset stronger than every sunrise.", author: "Warrior Wisdom", category: "Warrior" },
];